version: '3.3'
services:
  client:
    build: ./client
    container_name: client_node
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - './client:/home/client_node/app'
      - '/home/client_node/app/node_modules'
    networks:
      - my-network
  server:
    container_name: server_node
    image: 'node:latest'
    working_dir: /home/server_node/app
    env_file:
      - .env
    command:
      - /bin/sh
      - '-c'
      - 'npm install bcrypt mongoose express jsonwebtoken nodemon && npm start'
    ports:
      - '3001:3001'
    volumes:
      - './server:/home/server_node/app'
    links:
      - mongo
    networks:
      - my-network
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
    - ./mongo:/data/db
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
